<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

namespace GPBMetadata;

class Addressbook
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a1161646472657373626f6f6b2e70726f746f1202706222330a05" .
            "436c617373120b0a036e756d180120012805121d0a0873747564656e7473" .
            "18022003280b320b2e70622e53747564656e74223a0a0753747564656e74" .
            "120c0a046e616d65180120012809120b0a0361676518022001280512140a" .
            "0373657818032001280e32072e70622e5365782a190a0353657812070a03" .
            "4d414e100012090a05574f4d414e1001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

