<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 班级
 *
 * Generated from protobuf message <code>pb.Class</code>
 */
class PBClass extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     */
    protected $num = 0;
    /**
     * Generated from protobuf field <code>repeated .pb.Student students = 2;</code>
     */
    private $students;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $num
     *     @type \Pb\Student[]|\Google\Protobuf\Internal\RepeatedField $students
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Addressbook::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     * @return int
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * Generated from protobuf field <code>int32 num = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt32($var);
        $this->num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Student students = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStudents()
    {
        return $this->students;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Student students = 2;</code>
     * @param \Pb\Student[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStudents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Student::class);
        $this->students = $arr;

        return $this;
    }

}

